services:
  - type: web
    name: certificate-verification-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /api/health
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: AI_SERVICE_URL
        sync: false
      - key: VERIFICATION_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BLOCKCHAIN_RPC_URL
        sync: false
      - key: BLOCKCHAIN_PRIVATE_KEY
        sync: false
      - key: BLOCKCHAIN_CONTRACT_ADDRESS
        sync: false
      - key: BLOCKCHAIN_CHAIN_ID
        value: "80002"

  - type: web
    name: certificate-verification-ai
    runtime: docker
    dockerfilePath: ./ai-service/Dockerfile
    dockerContext: ./ai-service
    healthCheckPath: /health
